### PR TITLE
Update Godot to 3.6

### PR DESCRIPTION
**Pull request by dulvui**
I would like to update my to games Ball2Box and Pocket Broomball to Godot 3.6.

### CODE REVIEW

**Comment by MateusRodCosta** [comment]
While I am not the main maintainer of this repo, I have added the Godot 4.2 and Godot 4.3  BaseApps and also have been updating some of them to fdo 24.08 (just opened PRs for 3.5 and 4.3).

If I may, I would suggest the following changes on this PR:

- Change the fdo runtime from 22.08 to 24.08
- Update the `shared-modules` submodule to latest version (just run `git submodule update --remote` and commit the change)
- Consider updating SCons if it doesn't break the build (you can copy that from the 4.3 branch)

I would say the first one is essential (as 22.08 will likely be EOL soon), the second one is a good-to-have and the third one is optional.

**Comment by dulvui** [comment]
Thanks a lot for the suggestions! I updated the runtime to 24.08 and the git sub modules.
Updating the git sub modules didn't really change something on git, is that correct?

**Comment by MateusRodCosta** [comment]
> Thanks a lot for the suggestions! I updated the runtime to 24.08 and the git sub modules. Updating the git sub modules didn't really change something on git, is that correct?

Hmm, when I do the shared-modules update, generally VS Code shows me the shared modules reference in the VCS section.  Checking the diff, it tells me what was the previous version and what is the current one.
So I don't remember how it looks via the CLI.

If it didn't happen then the git submodule update command didn't work. Was the submodule initialized beforehand?

Try these commands:

- `git submodule init` 
- `git submodule update`
- `git submodule update --remote `

If this fails then I have no idea how to help =/
Do remember to check `git status` as I believe the modified submodule reference will show up there.

**Comment by MateusRodCosta** [comment]
In any case builds seem to be failing with

```
scons: Reading SConscript files ...
Warning: Speech Dispatcher development libraries not found. Disabling Text-to-Speech support.
Error: The `use_lto` and `use_thinlto` boolean options have been unified to `lto=<none|thin|full>`.
       Please adjust your scripts accordingly.
FB: host_command_exited_cb 1984154 65280
```

@Calinou Thoughts on this?

**Comment by dulvui** [comment]
Thanks, I didn't initialize the sub module and now I can see changes when doing so.
Everything up to date now.

**Comment by MateusRodCosta** [comment]
@dulvui Consider doing the same as https://github.com/flathub/org.godotengine.godot.BaseApp/pull/43/commits/11332bc49803bcd01382dbd8ceae2642f59f7ba5 to upgrade SCons.

Also, build is still failing, apparently you have to go on this section:

https://github.com/dulvui/org.godotengine.godot.BaseApp/blob/fe98c1279b85362dad0eb25614d1f9e8ea448912/org.godotengine.godot.BaseApp.yaml#L8-L14

And change `SCONS_FLAGS_EXTRA: use_lto=yes` to `SCONS_FLAGS_EXTRA: lto=full`

At least according to the error message:

```
Error: The `use_lto` and `use_thinlto` boolean options have been unified to `lto=<none|thin|full>`.
       Please adjust your scripts accordingly.
FB: host_command_exited_cb 2064136 65280
```

**Comment by dulvui** [comment]
@MateusRodCosta okay thanks, it's using scons 4.8.0 now.

**Comment by Calinou** [comment]
For TTS support, see https://github.com/flathub/org.godotengine.Godot/issues/122. The same fix should be applied here in a separate PR.

There are some merge conflicts that need to be resolved before I can merge this. See [PR workflow](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase) for instructions on rebasing 🙂 

(Use `git rebase branch/3.6` here, as you're rebasing on top of that branch, not `master`.)

**Comment by MateusRodCosta** [comment]
@Calinou Out of curiosity, should the same process for TTS support be done for 3.5(-23.08,-24.08) and 4.3(-24.08)?

**Comment by dulvui** [comment]
@Calinou I did `git rebase branch/3.6` but nothing changed, since I'm already on branch/3.6
Github offers me to resolve the conflict here in the PR, can I also do that?
image

**Comment by MateusRodCosta** [comment]
@dulvui Since you are already on `branch/3.6` locally, maybe try rebasing on top of `upstream/branch/3.6`?

**Comment by MateusRodCosta** [comment]
I think what you really want to do now is a force push (`git push origin HEAD --force`)

**Comment by dulvui** [comment]
Sorry for the mess, @MateusRodCosta you are right, I had my local branch also named `branch/3.6`
I was trying now to rename my `branch/3.6` to `update-3.6` and then sync and rebase it to the actual `origin/branch/3.6`

**Comment by MateusRodCosta** [comment]
It seems you reverted everything =/

**Comment by dulvui** [comment]
Sorry again for the mess, I opened a new PR here that should be fine
https://github.com/flathub/org.godotengine.godot.BaseApp/pull/45

**Pull request closed without merging**
